title: Dylan Parker
description: > # this means to ignore newlines until "baseurl:"
  Dylan Parker Full Stack Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codecave.app" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Dylan Parker
tagline: Full Stack Developer
about-description: > # Add Discription
  Hello my name is Dylan Parker. I'm a husband, father, and full stack developer. Head on over to the blog
  to see what's been going on!
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: dylan.parker@codecave.app # Add your Email address
phone: # Add your Phone number
website: https://codecave.app # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: dgparker # Add your Github handle
twitter: '@dgparker_' # Add your Twitter handle
slack: The Code Cave
slack_url: https://join.slack.com/t/the-code-cave/shared_invite/enQtMzkwODc4NDUzMDQzLWEyNTgwZDEyMTI0NjNhOTUxODQ3Zjc5N2Q2ODM2ZDhmZjc2YWI1NGI1NmM1NTk2NWM2ZThhOGU0NDA2MDYzNGY
discord: The Code Cave
discord_url: https://discord.gg/McEGpg

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
