title: Dylan Parker
description: > # this means to ignore newlines until "baseurl:"
  Dylan Parker Full Stack Developer
baseurl: "/dylanparker" # the subpath of your site, e.g. /blog
url: "https://dgparker.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Dylan Parker
tagline: Full Stack Developer
about-description: > # Add Discription
  Hello my name is Dylan Parker. I'm a husband, father, and full stack developer.
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: dgparker5150@gmail.com # Add your Email address
phone: 702 934 2619 # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: dgparker # Add your Github handle
twitter: '@dgparker_' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
